#!/bin/bash
perl -e '$w=0; $s=0; $w=hex(join("", map { sprintf "%02x", index("water", $_) } split //, $ENV{WATER})); $s=hex(join("", map { sprintf "%02x", index("stir", $_) } split //, $ENV{STIR})); $sum=$w+$s; @digits=split //, "bestchol"; $res=""; while($sum>0) { $res=$digits[$sum%8].$res; $sum=int($sum/8) } print "$res\n";'
