#!/bin/bash
WATER_DEC=$(echo "$WATER" | perl -e 'print unpack("H*", "ewwatratewa")') STIR_DEC=$(echo "$STIR" | perl -e 'print unpack("H*", "ti.itirtrtr")') RESULT=$((WATER_DEC + STIR_DEC)) echo "obase=18; $RESULT" | bc | perl -e 'print join("", map { ("shtbeolhc")[$_] } split(//, <STDIN>))'
