#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
rm -f /etc/nginx/sites-enabled/default
echo "server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx -t
nginx -g 'daemon off;'

